### PR TITLE
Support haskell-src-exts 1.18

### LINKED ISSUE #45: Build failure with haskell-src-exts 1.18
```
> /tmp/stackage-build8$ stack unpack hprotoc-2.4.0
Unpacked hprotoc-2.4.0 to /tmp/stackage-build8/hprotoc-2.4.0/
> /tmp/stackage-build8/hprotoc-2.4.0$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup configure --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --htmldir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --haddockdir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --flags=
Configuring hprotoc-2.4.0...
> /tmp/stackage-build8/hprotoc-2.4.0$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup build
Building hprotoc-2.4.0...
Preprocessing library hprotoc-2.4.0...
[ 1 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.Identifiers ( Text/ProtocolBuffers/ProtoCompile/Identifiers.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/Identifiers.o )
[ 2 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.BreakRecursion ( Text/ProtocolBuffers/ProtoCompile/BreakRecursion.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/BreakRecursion.o )
[ 3 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.Gen ( Text/ProtocolBuffers/ProtoCompile/Gen.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/Gen.o )

Text/ProtocolBuffers/ProtoCompile/Gen.hs:77:8: error:
    Not in scope: type constructor or class ‘SrcLoc’
```

### PR DESCRIPTION
**Pull request by tvh**
This fixes #45. It also drops compatibility with earlier versions however.

### CODE REVIEW

**Comment by tvh** [comment]
It compiles, but produces defective code as of now. I'll look into it.

**Comment by k-bx** [comment]
Wow! Huge thanks for starting it. Last time I started I gave up after an hour or so :)

**Comment by tvh** [comment]
I think it should work now. I only updated one stack.yaml to check it, but it should work for the others as well.

**Comment by k-bx** [comment]
@tvh can you please check riak-haskell-client with code generated by this version? I think you can just make a PR and see if Travis passes.

Thank you!

**Comment by tvh** [comment]
This version should generate code identical to the current HEAD. I checked this on our project and it worked perfectly. The diff between the old and new versions was empty.

**Comment by k-bx** [comment]
Ok, I ran `proto.sh` in `protobuf` dir of riak-haskell-client and all it did was this:

```
diff --git a/protobuf/src/Network/Riak/Protocol/MapOp.hs-boot b/protobuf/src/Network/Riak/Protocol/MapOp.hs-boot
index d82f85c..392a500 100644
--- a/protobuf/src/Network/Riak/Protocol/MapOp.hs-boot
+++ b/protobuf/src/Network/Riak/Protocol/MapOp.hs-boot
@@ -1,4 +1,4 @@
-{-# LANGUAGE BangPatterns, DeriveDataTypeable, DeriveGeneric, FlexibleInstances, MultiParamTypeClasses, CPP#-}
+{-# LANGUAGE BangPatterns, DeriveDataTypeable, DeriveGeneric, FlexibleInstances, MultiParamTypeClasses #-}
 {-# OPTIONS_GHC  -fno-warn-unused-imports #-}
 module Network.Riak.Protocol.MapOp (MapOp) where
 import qualified Prelude as Prelude'
@@ -17,15 +17,11 @@ instance Prelude'.Eq MapOp

 instance Prelude'.Ord MapOp

-#if __GLASGOW_HASKELL__ <= 708
 instance Prelude'.Typeable MapOp
-#endif

 instance Prelude'.Data MapOp

-#if __GLASGOW_HASKELL__ <= 708
 instance Prelude'.Generic MapOp
-#endif

 instance P'.Mergeable MapOp
```

I guess it should be fine (compiles fine for me on 8.0).

**Comment by k-bx** [comment]
@tvh do you see why travis fails for 7.10? I think we can drop earlier, but need to add 8.2 imho

**Comment by tvh** [comment]
I think it should pass now. The stackage snapshot had a version of haskell-src-exts that was too old. 1.18 and 1.19 should work fine though.

I'm not sure where those CPP Pragmas came from in riak-haskell-client. Maybe they were added manually to support GHC 7.8?

**Comment by k-bx** [comment]
@tvh thank you very much for the work! Released under 2.4.5. version

**Pull request merged**
