### PR TITLE
Fix #38: Not GHC-8.0.1 compatible

### LINKED ISSUE #38: Not GHC 8.0.1 compatible
Building this package fails because of some ambiguity introduced by ghc-8.0.1. For example:

```
 /private/var/folders/xp/8fbnz73x77786vmh_8zhct3w0000gn/T/stack38582/protocol-buffers-2.3.1/Text/ProtocolBuffers/Get.hs:211:50: error:
        • Could not deduce (Integral a7)
            arising from a use of ‘fromIntegral’
          from the context: (Num s, Integral s, Bits s)
            bound by the type signature for:
                       decode7unrolled :: (Num s, Integral s, Bits s) => Get s
            at Text/ProtocolBuffers/Get.hs:133:1-64
          The type variable ‘a7’ is ambiguous
          Relevant bindings include
            b'A :: a7 (bound at Text/ProtocolBuffers/Get.hs:210:17)
          These potential instances exist:
            instance Integral Int32 -- Defined in ‘GHC.Int’
            instance Integral Int64 -- Defined in ‘GHC.Int’
            instance Integral Word16 -- Defined in ‘GHC.Word’
            ...plus six others
            ...plus six instances involving out-of-scope types
            (use -fprint-potential-instances to see them all)
        • In the first argument of ‘shiftL’, namely ‘fromIntegral b'A’
          In the second argument of ‘(.|.)’, namely
            ‘(fromIntegral b'A `shiftL` 63)’
          In the first argument of ‘ok’, namely
            ‘(val'9 .|. (fromIntegral b'A `shiftL` 63))’
```

Full log: https://gist.github.com/MaxDaten/9fbd4213bbfc168fcc90917de1a11cba

I'm working on a PR.

### PR DESCRIPTION
**Pull request by MaxDaten**
Added scoped types `Word8` to resolve ambiguity

### CODE REVIEW

**Comment by k-bx** [comment]
@MaxDaten fails with a need to install a fresh `happy`

**Comment by MaxDaten** [comment]
I will try to fix this tomorrow.

**Comment by MaxDaten** [comment]
It's ready now. Please check the .travis.yml, if it's the changes are adequate, I'm not a travis expert.

**Comment by k-bx** [comment]
@MaxDaten thank you very much! Uploaded as 2.4.0

**Pull request merged**
